### ISSUE TITLE
Recipy doesn't install with python3 inside buildout

### ISSUE THREAD

**Issue by reinout** [reinout/collective.recipe.sphinxbuilder#1]
This is the traceback I get on python 3:

    Traceback (most recent call last):
      File "/code/eggs/setuptools-23.1.0-py3.5.egg/setuptools/sandbox.py", line 154, in save_modules
      File "/code/eggs/setuptools-23.1.0-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/code/eggs/setuptools-23.1.0-py3.5.egg/setuptools/sandbox.py", line 243, in run_setup
      File "/code/eggs/setuptools-23.1.0-py3.5.egg/setuptools/sandbox.py", line 273, in run
      File "/code/eggs/setuptools-23.1.0-py3.5.egg/setuptools/sandbox.py", line 242, in runner
      File "/code/eggs/setuptools-23.1.0-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
      File "/tmp/easy_install-nf51bu4r/collective.recipe.sphinxbuilder-0.8.2/setup.py", line 28, in <module>
        'mock',
      File "/tmp/easy_install-nf51bu4r/collective.recipe.sphinxbuilder-0.8.2/setup.py", line 9, in read
        ])
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 180: ordinal not in range(128)

Weird: anything I try with a downloaded 0.8.2 works fine.

**Comment by reinout** [comment]
Fixed with release 0.9.
